// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsF_sk6ZFPiI7WUv2ggNIAfVBdYC-9Ngg',
    appId: '1:606616450115:web:bf479ac4397dfcfbd350f6',
    messagingSenderId: '606616450115',
    projectId: 'housesware',
    authDomain: 'housesware.firebaseapp.com',
    storageBucket: 'housesware.appspot.com',
    measurementId: 'G-RFYPRB74ZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI7ZuAn4RvIn62kooqerfbp5GX_gToejo',
    appId: '1:606616450115:android:a552dfc28ae7b890d350f6',
    messagingSenderId: '606616450115',
    projectId: 'housesware',
    storageBucket: 'housesware.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbhLyZwyt0iZSdDNr8SI9nX_1n1MMgrh8',
    appId: '1:606616450115:ios:9940bb7d89bec73ed350f6',
    messagingSenderId: '606616450115',
    projectId: 'housesware',
    storageBucket: 'housesware.appspot.com',
    iosClientId: '606616450115-d47128p007jb2t813s0npm1b9tkajamn.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertySwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbhLyZwyt0iZSdDNr8SI9nX_1n1MMgrh8',
    appId: '1:606616450115:ios:9940bb7d89bec73ed350f6',
    messagingSenderId: '606616450115',
    projectId: 'housesware',
    storageBucket: 'housesware.appspot.com',
    iosClientId: '606616450115-d47128p007jb2t813s0npm1b9tkajamn.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertySwap',
  );
}
