// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM6QMcMEj8UkTWE_fhR34T3eA2CvADF6M',
    appId: '1:14504729652:web:2aead8568119cfde8dbe61',
    messagingSenderId: '14504729652',
    projectId: 'safyan-56ecc',
    authDomain: 'safyan-56ecc.firebaseapp.com',
    storageBucket: 'safyan-56ecc.appspot.com',
    measurementId: 'G-8LK06HPGBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1euopLjzS7zDqQuat3i471zl7ntG9Wu8',
    appId: '1:14504729652:android:dbc164b48e6e32878dbe61',
    messagingSenderId: '14504729652',
    projectId: 'safyan-56ecc',
    storageBucket: 'safyan-56ecc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRVaxy26rW65_Jt2XpzKZ92n2hepQPSEM',
    appId: '1:14504729652:ios:c1d0d25aa09411e28dbe61',
    messagingSenderId: '14504729652',
    projectId: 'safyan-56ecc',
    storageBucket: 'safyan-56ecc.appspot.com',
    iosClientId: '14504729652-3m1g8sm5j55h8e3si8e4vc7sk8rbkdv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertySwap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRVaxy26rW65_Jt2XpzKZ92n2hepQPSEM',
    appId: '1:14504729652:ios:c1d0d25aa09411e28dbe61',
    messagingSenderId: '14504729652',
    projectId: 'safyan-56ecc',
    storageBucket: 'safyan-56ecc.appspot.com',
    iosClientId: '14504729652-3m1g8sm5j55h8e3si8e4vc7sk8rbkdv5.apps.googleusercontent.com',
    iosBundleId: 'com.example.propertySwap',
  );
}
